/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.util.FormMode;
import java.util.List;
import javax.swing.JOptionPane;
import domain.Movie;
import domain.Director;
import controller.Controller;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mihailo
 */
public class FrmMovie extends javax.swing.JDialog {

    /**
     * Creates new form FrmFilm
     */
    public FrmMovie(java.awt.Frame parent, boolean modal, FormMode mode, Movie movie) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Movie form");
        
        try {
            prepareView(mode, movie);
        } catch (Exception ex) {
            Logger.getLogger(FrmMovie.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "There was an error", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMoveID = new javax.swing.JLabel();
        txtMovieID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtReleaseDate = new javax.swing.JTextField();
        lblReleaseDate = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        cbDirector = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        btnEnableChanges = new javax.swing.JButton();
        btnCanel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblMoveID.setText("ID:");

        lblName.setText("Name:");

        lblReleaseDate.setText("Release date:");

        lblDirector.setText("Director:");

        lblDescription.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblScore.setText("Score:");

        btnEnableChanges.setText("Enable changes");
        btnEnableChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableChangesActionPerformed(evt);
            }
        });

        btnCanel.setText("Cancel");
        btnCanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnableChanges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReleaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMoveID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMovieID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtReleaseDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtScore, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDirector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDirector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoveID)
                    .addComponent(txtMovieID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReleaseDate)
                    .addComponent(txtReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScore)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDirector)
                    .addComponent(cbDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescription)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd)
                    .addComponent(btnEnableChanges)
                    .addComponent(btnCanel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //odradi validaciju polja prilikom unosa
        
        Movie movie = new Movie();
        
        movie.setMovieID(Integer.parseInt(txtMovieID.getText().trim()));
        movie.setName(txtName.getText().trim());
        movie.setReleaseDate(LocalDate.now());
        movie.setDescription(txtDescription.getText().trim());
        movie.setDirector((Director)cbDirector.getSelectedItem());
        
        JOptionPane.showMessageDialog(this,"Added movie: " + movie.getName(), "Success!", JOptionPane.INFORMATION_MESSAGE);
        
        try {
            Controller.getInstance().addMovie(movie);
        } catch (Exception ex) {
            Logger.getLogger(FrmMovie.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Movie not saved. Try again.", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        txtMovieID.setText(null);
        txtName.setText(null);
        txtReleaseDate.setText(null);
        txtDescription.setText(null);
        cbDirector.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Movie movie = new Movie();
        
        movie.setMovieID(Integer.parseInt(txtMovieID.getText().trim()));
        movie.setName(txtName.getText().trim());
        movie.setReleaseDate(LocalDate.now());
        movie.setDescription(txtDescription.getText().trim());
        movie.setDirector((Director)cbDirector.getSelectedItem());
        movie.setScore(0);
        
        int check = JOptionPane.showConfirmDialog(this, "Are you sure?", "Delete movie", 
                JOptionPane.YES_NO_OPTION);
        
        if (check == JOptionPane.YES_OPTION) {
            Controller.getInstance().removeMovie(movie);
            JOptionPane.showMessageDialog(this, "Deleted movie: " + movie.getName(), "Info", JOptionPane.INFORMATION_MESSAGE);
        }
      
        this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Movie movie = new Movie() {
            {
                setMovieID(Integer.parseInt(txtMovieID.getText().trim()));
                setName(txtName.getText().trim());
                setReleaseDate(LocalDate.now());
                setDescription(txtDescription.getText().trim());
                setDirector((Director)cbDirector.getSelectedItem());
                setScore(0);
            }
        };
        
        int check = JOptionPane.showConfirmDialog(this, "Are you sure?", "Update movie", 
                JOptionPane.YES_NO_OPTION);
        
        if (check == JOptionPane.YES_OPTION) {
            Controller.getInstance().updateMovie(movie);
            JOptionPane.showMessageDialog(this, "Updated movie: " + movie.getName(), "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCanelActionPerformed

    private void btnEnableChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableChangesActionPerformed
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnCanel.setEnabled(true);
        btnEnableChanges.setEnabled(true);
        btnUpdate.setEnabled(true);

        txtMovieID.setEditable(true);
        txtName.setEditable(true);
        txtReleaseDate.setEditable(true);
        txtScore.setEditable(false);
        txtDescription.setEditable(true);
        cbDirector.setEnabled(true);
    }//GEN-LAST:event_btnEnableChangesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCanel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEnableChanges;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Object> cbDirector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblMoveID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblReleaseDate;
    private javax.swing.JLabel lblScore;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtMovieID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReleaseDate;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables

    private void prepareView(FormMode mode, Movie movie)throws Exception{
        fillCB();
        setUpComponents(mode, movie);
    }
    
    private void fillCB() throws Exception{
        cbDirector.removeAllItems();
        List<Director> directors = Controller.getInstance().getAllDirectors();
        
        for (Director director : directors) {
            cbDirector.addItem(director);
        }
    }    

    private void setUpComponents(FormMode mode, Movie movie) {
        switch(mode) {
            case FORM_ADD:
                btnAdd.setEnabled(true);
                btnDelete.setEnabled(false);
                btnCanel.setEnabled(true);
                btnEnableChanges.setEnabled(false);
                btnUpdate.setEnabled(false);
                
                txtScore.setText(String.valueOf(0));
                txtScore.setEditable(false);
                break;
            case FORM_VIEW:
                btnAdd.setEnabled(false);
                btnDelete.setEnabled(true);
                btnCanel.setEnabled(true);
                btnEnableChanges.setEnabled(true);
                btnUpdate.setEnabled(false);
                
                txtMovieID.setText(String.valueOf(movie.getMovieID()));
                txtName.setText(movie.getName());
                txtReleaseDate.setText(String.valueOf(movie.getReleaseDate()));
                txtScore.setText(String.valueOf(movie.getScore()));
                txtDescription.setText(movie.getDescription());
                cbDirector.setSelectedItem(movie.getDirector());
                
                txtMovieID.setEditable(false);
                txtName.setEditable(false);
                txtReleaseDate.setEditable(false);
                txtScore.setEditable(false);
                txtDescription.setEditable(false);
                cbDirector.setEnabled(false);
                break;
            case FORM_EDIT:
                break;
        }
    }
}
