/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Mihailo
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserStatistics = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jmMovie = new javax.swing.JMenu();
        jmiNewMovie = new javax.swing.JMenuItem();
        jmiViewAllMovies = new javax.swing.JMenuItem();
        jmDirector = new javax.swing.JMenu();
        jmiNewDirector = new javax.swing.JMenuItem();
        jmiViewAllDirectors = new javax.swing.JMenuItem();
        jmActor = new javax.swing.JMenu();
        jmiNewActor = new javax.swing.JMenuItem();
        jmiViewAllActors = new javax.swing.JMenuItem();
        jMenuAccount = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurrentUser.setText("Current user:");

        tblUserStatistics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "System role", "Collection size", "Review count", "Highest rated movie", "Score"
            }
        ));
        jScrollPane1.setViewportView(tblUserStatistics);

        jLabel1.setText("User statistics:");

        jmMovie.setText("Movie");

        jmiNewMovie.setText("New");
        jmMovie.add(jmiNewMovie);

        jmiViewAllMovies.setText("View all");
        jmMovie.add(jmiViewAllMovies);

        jMenuBarMain.add(jmMovie);

        jmDirector.setText("Director");

        jmiNewDirector.setText("New");
        jmDirector.add(jmiNewDirector);

        jmiViewAllDirectors.setText("View all");
        jmDirector.add(jmiViewAllDirectors);

        jMenuBarMain.add(jmDirector);

        jmActor.setText("Actor");

        jmiNewActor.setText("New");
        jmActor.add(jmiNewActor);

        jmiViewAllActors.setText("View all");
        jmActor.add(jmiViewAllActors);

        jMenuBarMain.add(jmActor);

        jMenuAccount.setText("Account");

        jmiLogout.setText("Logout");
        jMenuAccount.add(jmiLogout);

        jMenuBarMain.add(jMenuAccount);

        jMenuAbout.setText("About");

        jmiAboutSoftware.setText("Software");
        jMenuAbout.add(jmiAboutSoftware);

        jMenuBarMain.add(jMenuAbout);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblCurrentUser))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCurrentUser)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenu jMenuAccount;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmActor;
    private javax.swing.JMenu jmDirector;
    private javax.swing.JMenu jmMovie;
    private javax.swing.JMenuItem jmiAboutSoftware;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiNewActor;
    private javax.swing.JMenuItem jmiNewDirector;
    private javax.swing.JMenuItem jmiNewMovie;
    private javax.swing.JMenuItem jmiViewAllActors;
    private javax.swing.JMenuItem jmiViewAllDirectors;
    private javax.swing.JMenuItem jmiViewAllMovies;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JTable tblUserStatistics;
    // End of variables declaration//GEN-END:variables

    public void jmiNewMovieAddActionListener(ActionListener actionListener) {
        jmiNewMovie.addActionListener(actionListener);
    }

    public void jmiViewAllMoviesActionListener(ActionListener actionListener) {
        jmiViewAllMovies.addActionListener(actionListener);
    }
    
    public void jmiNewDirectorAddActionListener(ActionListener actionListener) {
        jmiNewDirector.addActionListener(actionListener);
    }
    
    public void jmiViewAllDirectorsActionListener(ActionListener actionListener) {
        jmiViewAllDirectors.addActionListener(actionListener);
    }
    
    public void jmiNewActorAddActionListener(ActionListener actionListener) {
        jmiNewActor.addActionListener(actionListener);
    }
    
    public void jmiViewAllActorsActionListener(ActionListener actionListener) {
        jmiViewAllActors.addActionListener(actionListener);
    }
    
    public void jmiLogoutActionListener(ActionListener actionListener) {
        jmiLogout.addActionListener(actionListener);
    }
    
    public JLabel getLblCurrentUser () {
        return lblCurrentUser;
    }

    public JTable getTblUserStatistics() {
        return tblUserStatistics;
    }
    
    
}
