/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.event.ActionListener;

/**
 *
 * @author Mihailo
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        super("Main form");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarMain = new javax.swing.JMenuBar();
        jmMovie = new javax.swing.JMenu();
        jmiNewMovie = new javax.swing.JMenuItem();
        jmiViewAllMovies = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmMovie.setText("Movie");

        jmiNewMovie.setText("New");
        jmMovie.add(jmiNewMovie);

        jmiViewAllMovies.setText("View all");
        jmMovie.add(jmiViewAllMovies);

        jMenuBarMain.add(jmMovie);

        jMenuAbout.setText("About");

        jmiAboutSoftware.setText("Software");
        jMenuAbout.add(jmiAboutSoftware);

        jMenuBarMain.add(jMenuAbout);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jmMovie;
    private javax.swing.JMenuItem jmiAboutSoftware;
    private javax.swing.JMenuItem jmiNewMovie;
    private javax.swing.JMenuItem jmiViewAllMovies;
    // End of variables declaration//GEN-END:variables

    public void jmiNewMovieAddActionListener(ActionListener actionListener) {
        jmiNewMovie.addActionListener(actionListener);
    }

    public void jmiViewAllMoviesActionListener(ActionListener actionListener) {
        jmiViewAllMovies.addActionListener(actionListener);
    }
}
