/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import com.sun.source.util.TaskEvent;
import forme.util.RezimRadaForme;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import klase.Film;
import klase.Reziser;
import kontroler.Kontroler;

/**
 *
 * @author Mihailo
 */
public class FrmFilm extends javax.swing.JDialog {

    /**
     * Creates new form FrmFilm
     */
    public FrmFilm(java.awt.Frame parent, boolean modal, RezimRadaForme rezim, Film film) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Forma za rad sa filmovima");
        
        pripremiProzor(rezim, film);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIFilmID = new javax.swing.JLabel();
        txtFilmID = new javax.swing.JTextField();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtDatumIzdanja = new javax.swing.JTextField();
        lblDatumIzdanja = new javax.swing.JLabel();
        lblReziser = new javax.swing.JLabel();
        lblOpis = new javax.swing.JLabel();
        cbReziser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnUkloni = new javax.swing.JButton();
        lblProsecnaOcena = new javax.swing.JLabel();
        txtProsecnaOcena = new javax.swing.JTextField();
        btnOmoguciIzmene = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIFilmID.setText("ID:");

        lblNaziv.setText("Naziv:");

        lblDatumIzdanja.setText("Datum izdanja:");

        lblReziser.setText("Režiser:");

        lblOpis.setText("Opis:");

        txtOpis.setColumns(20);
        txtOpis.setLineWrap(true);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.setEnabled(false);
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnUkloni.setText("Ukloni");
        btnUkloni.setEnabled(false);
        btnUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniActionPerformed(evt);
            }
        });

        lblProsecnaOcena.setText("Prosečna ocena:");

        btnOmoguciIzmene.setText("Omogući izmene");
        btnOmoguciIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmoguciIzmeneActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIFilmID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatumIzdanja)
                            .addComponent(lblProsecnaOcena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFilmID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDatumIzdanja, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProsecnaOcena, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReziser, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(cbReziser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIzmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOdustani)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOmoguciIzmene)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUkloni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDodaj)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIFilmID)
                    .addComponent(txtFilmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumIzdanja)
                    .addComponent(txtDatumIzdanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProsecnaOcena)
                    .addComponent(txtProsecnaOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReziser)
                    .addComponent(cbReziser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUkloni)
                    .addComponent(btnIzmeni)
                    .addComponent(btnDodaj)
                    .addComponent(btnOmoguciIzmene)
                    .addComponent(btnOdustani))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        //odradi validaciju polja prilikom unosa
        
        Film film = new Film();
        
        film.setFilmID(Integer.parseInt(txtFilmID.getText().trim()));
        film.setNaziv(txtNaziv.getText().trim());
        film.setDatumIzdanja(new Date()); // OBAVEZNO PITATI ZA PREPORUKE STO SE TICE RADA SA DATUMIMA
        film.setOpis(txtOpis.getText().trim());
        film.setReziser((Reziser)cbReziser.getSelectedItem());
        
        JOptionPane.showMessageDialog(this,"Unet film: " + film.getNaziv(), "Uspesan unos filma!", JOptionPane.INFORMATION_MESSAGE);
        
        Kontroler.vratiInstancu().dodajFilm(film);
        
        txtFilmID.setText(null);
        txtNaziv.setText(null);
        txtDatumIzdanja.setText(null);
        txtOpis.setText(null);
        cbReziser.setSelectedIndex(0);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniActionPerformed
        Film film = new Film();
        
        film.setFilmID(Integer.parseInt(txtFilmID.getText().trim()));
        film.setNaziv(txtNaziv.getText().trim());
        film.setDatumIzdanja(new Date());
        film.setOpis(txtOpis.getText().trim());
        film.setReziser((Reziser)cbReziser.getSelectedItem());
        film.setProsecnaOcena(0);
        
        int provera = JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Brisanje filma", 
                JOptionPane.YES_NO_OPTION);
        
        if (provera == JOptionPane.YES_OPTION) {
            Kontroler.vratiInstancu().ukloniFilm(film);
            JOptionPane.showMessageDialog(this, "Uklonjen film: " + film.getNaziv(), "Info", JOptionPane.INFORMATION_MESSAGE);
        }
      
        this.dispose();
    }//GEN-LAST:event_btnUkloniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Film film = new Film();
        
        film.setFilmID(Integer.parseInt(txtFilmID.getText().trim()));
        film.setNaziv(txtNaziv.getText().trim());
        film.setDatumIzdanja(new Date());
        film.setOpis(txtOpis.getText().trim());
        film.setReziser((Reziser)cbReziser.getSelectedItem());
        film.setProsecnaOcena(0);
        
        int provera = JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Izmena filma", 
                JOptionPane.YES_NO_OPTION);
        
        if (provera == JOptionPane.YES_OPTION) {
            Kontroler.vratiInstancu().izmeniFilm(film);
            JOptionPane.showMessageDialog(this, "Izmenjen film: " + film.getNaziv(), "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnOmoguciIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmoguciIzmeneActionPerformed
        btnDodaj.setEnabled(false);
        btnUkloni.setEnabled(false);
        btnOdustani.setEnabled(true);
        btnOmoguciIzmene.setEnabled(true);
        btnIzmeni.setEnabled(true);

        txtFilmID.setEditable(true);
        txtNaziv.setEditable(true);
        txtDatumIzdanja.setEditable(true);
        txtProsecnaOcena.setEditable(false);
        txtOpis.setEditable(true);
        cbReziser.setEnabled(true);
    }//GEN-LAST:event_btnOmoguciIzmeneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnOmoguciIzmene;
    private javax.swing.JButton btnUkloni;
    private javax.swing.JComboBox<Object> cbReziser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumIzdanja;
    private javax.swing.JLabel lblIFilmID;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblProsecnaOcena;
    private javax.swing.JLabel lblReziser;
    private javax.swing.JTextField txtDatumIzdanja;
    private javax.swing.JTextField txtFilmID;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtProsecnaOcena;
    // End of variables declaration//GEN-END:variables

    private void pripremiProzor(RezimRadaForme rezim, Film film) {
        ucitajCB();
        podesiKomponente(rezim, film);
    }
    
    private void ucitajCB() {
        cbReziser.removeAllItems();
        List<Reziser> reziseri = Kontroler.vratiInstancu().vratiSveRezisere();
        
        for (Reziser reziser : reziseri) {
            cbReziser.addItem(reziser);
        }
    }    

    private void podesiKomponente(RezimRadaForme rezim, Film film) {
        switch(rezim) {
            case FORMA_DODAVANJE:
                btnDodaj.setEnabled(true);
                btnUkloni.setEnabled(false);
                btnOdustani.setEnabled(true);
                btnOmoguciIzmene.setEnabled(false);
                btnIzmeni.setEnabled(false);
                
                txtProsecnaOcena.setText(String.valueOf(0));
                txtProsecnaOcena.setEditable(false);
                break;
            case FORMA_PRIKAZ:
                btnDodaj.setEnabled(false);
                btnUkloni.setEnabled(true);
                btnOdustani.setEnabled(true);
                btnOmoguciIzmene.setEnabled(true);
                btnIzmeni.setEnabled(false);
                
                txtFilmID.setText(String.valueOf(film.getFilmID()));
                txtNaziv.setText(film.getNaziv());
                txtDatumIzdanja.setText(String.valueOf(film.getDatumIzdanja()));
                txtProsecnaOcena.setText(String.valueOf(film.getProsecnaOcena()));
                txtOpis.setText(film.getOpis());
                cbReziser.setSelectedItem(film.getReziser());
                
                txtFilmID.setEditable(false);
                txtNaziv.setEditable(false);
                txtDatumIzdanja.setEditable(false);
                txtProsecnaOcena.setEditable(false);
                txtOpis.setEditable(false);
                cbReziser.setEnabled(false);
                break;
            case FORMA_IZMENA:
                break;
        }
    }
}
