/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import com.sun.source.util.TaskEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import klase.Film;
import klase.Reziser;
import kontroler.Kontroler;

/**
 *
 * @author Mihailo
 */
public class FrmFilm extends javax.swing.JDialog {

    /**
     * Creates new form FrmFilm
     */
    public FrmFilm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Forma za rad sa filmovima");
        
        ucitajCB();
        
        txtProsecnaOcena.setText(String.valueOf(0));
        txtProsecnaOcena.setEditable(false);
        btnUkloni.setEnabled(false);
        btnIzmeni.setEnabled(false);
        btnDodaj.setEnabled(true);
    }
    
    public FrmFilm(java.awt.Frame parent, boolean modal, Film film) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Forma za rad sa filmovima");
        
        pripremiProzor(film);
        
        
        btnUkloni.setEnabled(true);
        btnIzmeni.setEnabled(true);
        btnDodaj.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIFilmID = new javax.swing.JLabel();
        txtFilmID = new javax.swing.JTextField();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtDatumIzdanja = new javax.swing.JTextField();
        lblDatumIzdanja = new javax.swing.JLabel();
        lblReziser = new javax.swing.JLabel();
        lblOpis = new javax.swing.JLabel();
        cbReziser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        btnDodaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnUkloni = new javax.swing.JButton();
        lblProsecnaOcena = new javax.swing.JLabel();
        txtProsecnaOcena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblIFilmID.setText("ID:");

        lblNaziv.setText("Naziv:");

        lblDatumIzdanja.setText("Datum izdanja:");

        lblReziser.setText("Režiser:");

        lblOpis.setText("Opis:");

        txtOpis.setColumns(20);
        txtOpis.setLineWrap(true);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.setEnabled(false);
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnUkloni.setText("Ukloni");
        btnUkloni.setEnabled(false);
        btnUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUkloniActionPerformed(evt);
            }
        });

        lblProsecnaOcena.setText("Prosečna ocena:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReziser, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbReziser, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnUkloni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIzmeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDodaj))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIFilmID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatumIzdanja)
                            .addComponent(lblProsecnaOcena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProsecnaOcena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatumIzdanja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFilmID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIFilmID)
                    .addComponent(txtFilmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumIzdanja)
                    .addComponent(txtDatumIzdanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProsecnaOcena)
                    .addComponent(txtProsecnaOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReziser)
                    .addComponent(cbReziser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUkloni)
                    .addComponent(btnIzmeni)
                    .addComponent(btnDodaj))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        //odradi validaciju polja prilikom unosa
        
        Film film = new Film();
        
        film.setFilmID(Integer.parseInt(txtFilmID.getText().trim()));
        film.setNaziv(txtNaziv.getText().trim());
        film.setDatumIzdanja(new Date()); // OBAVEZNO PITATI ZA PREPORUKE STO SE TICE RADA SA DATUMIMA
        film.setOpis(txtOpis.getText().trim());
        film.setReziser((Reziser)cbReziser.getSelectedItem());
        
        JOptionPane.showMessageDialog(this,"Unet film: " + film.getNaziv(), "Uspesan unos filma!", JOptionPane.INFORMATION_MESSAGE);
        
        Kontroler.vratiInstancu().dodajFilm(film);
        
        txtFilmID.setText(null);
        txtNaziv.setText(null);
        txtDatumIzdanja.setText(null);
        txtOpis.setText(null);
        cbReziser.setSelectedIndex(-1);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUkloniActionPerformed
        Film film = new Film();
        
        film.setFilmID(Integer.parseInt(txtFilmID.getText().trim()));
        film.setNaziv(txtNaziv.getText().trim());
        film.setDatumIzdanja(new Date());
        film.setOpis(txtOpis.getText().trim());
        film.setReziser((Reziser)cbReziser.getSelectedItem());
        film.setProsecnaOcena(0);
        
        Kontroler.vratiInstancu().ukloniFilm(film);
        JOptionPane.showMessageDialog(this, "Uklonjen film: " + film.getNaziv(), "Info", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnUkloniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Film film = new Film();
        
        film.setFilmID(Integer.parseInt(txtFilmID.getText().trim()));
        film.setNaziv(txtNaziv.getText().trim());
        film.setDatumIzdanja(new Date());
        film.setOpis(txtOpis.getText().trim());
        film.setReziser((Reziser)cbReziser.getSelectedItem());
        film.setProsecnaOcena(0);
        
        Kontroler.vratiInstancu().izmeniFilm(film);
        JOptionPane.showMessageDialog(this, "Izmenjen film: " + film.getNaziv(), "Info", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnUkloni;
    private javax.swing.JComboBox<Object> cbReziser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatumIzdanja;
    private javax.swing.JLabel lblIFilmID;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblProsecnaOcena;
    private javax.swing.JLabel lblReziser;
    private javax.swing.JTextField txtDatumIzdanja;
    private javax.swing.JTextField txtFilmID;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtProsecnaOcena;
    // End of variables declaration//GEN-END:variables

    private void pripremiProzor(Film film) {
        ucitajCB();
        popuniPolja(film);
    }
    
    private void ucitajCB() {
        cbReziser.removeAllItems();
        List<Reziser> reziseri = Kontroler.vratiInstancu().vratiSveRezisere();
        
        for (Reziser reziser : reziseri) {
            cbReziser.addItem(reziser);
        }
    }

    private void popuniPolja(Film film) {
        txtFilmID.setText(String.valueOf(film.getFilmID()));
        txtNaziv.setText(film.getNaziv());
        txtDatumIzdanja.setText(String.valueOf(film.getDatumIzdanja()));
        cbReziser.setSelectedItem(film.getReziser());
        txtOpis.setText(film.getOpis());
    }

    
}
