/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import klase.Film;
import kontroler.Kontroler;

/**
 *
 * @author Mihailo
 */
public class FrmPrikazFilmova extends javax.swing.JDialog {

    /**
     * Creates new form FrmPrikazFilmova
     */
    public FrmPrikazFilmova(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        pripremiProzor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilmovi = new javax.swing.JTable();
        btnInformacije = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblFilmovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Datum izdanja", "Prosecna ocena", "Reziser"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFilmovi);

        btnInformacije.setText("Informacije");
        btnInformacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInformacije)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnInformacije)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacijeActionPerformed
        
    }//GEN-LAST:event_btnInformacijeActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformacije;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFilmovi;
    // End of variables declaration//GEN-END:variables

    private void pripremiProzor() {
        setTitle("Prikaz filmova");
        setLocationRelativeTo(null);
        
        popuniTabeluFilmova();
    }

    private void popuniTabeluFilmova() {
        List<Film> filmovi = Kontroler.vratiInstancu().vratiSveFilmove();
        DefaultTableModel dtm = (DefaultTableModel) tblFilmovi.getModel();
        
        for (Film film : filmovi) {
            Object[] redTabele = new Object[]{
                film.getFilmID(),
                film.getNaziv(),
                film.getDatumIzdanja(),
                film.getProsecnaOcena(),
                film.getReziser()
            };
            dtm.addRow(redTabele);
        }
    }
}
